GetKeyListMap(vcasesense:="Off")    { ; https://www.autohotkey.com/docs/v2/KeyList.htm
    str_keylist:="
(
LButton,LButton
RButton,RButton
MButton,MButton
XButton1,XButton1
XButton2,XButton2
WheelDown,WheelDown
WheelUp,WheelUp
WheelLeft,WheelLeft
WheelRight,WheelRight
CapsLock,CapsLock
Space,Space
Tab,Tab
Enter,Enter
Escape,Escape
Esc,Escape
Backspace,Backspace
BS,Backspace
ScrollLock,ScrollLock
Delete,Delete
Del,Delete
Insert,Insert
Ins,Insert
Home,Home
End,End
PgUp,PgUp
PgDn,PgDn
Up,Up
Down,Down
Left,Left
Right,Right
Numpad0,Numpad0
NumpadIns,NumpadIns
Numpad1,Numpad1
NumpadEnd,NumpadEnd
Numpad2,Numpad2
NumpadDown,NumpadDown
Numpad3,Numpad3
NumpadPgDn,NumpadPgDn
Numpad4,Numpad4
NumpadLeft,NumpadLeft
Numpad5,Numpad5
NumpadClear,NumpadClear
Numpad6,Numpad6
NumpadRight,NumpadRight
Numpad7,Numpad7
NumpadHome,NumpadHome
Numpad8,Numpad8
NumpadUp,NumpadUp
Numpad9,Numpad9
NumpadPgUp,NumpadPgUp
NumpadDot,NumpadDot
NumpadDel,NumpadDel
NumLock,NumLock
NumpadDiv,NumpadDiv
NumpadMult,NumpadMult
NumpadAdd,NumpadAdd
NumpadSub,NumpadSub
NumpadEnter,NumpadEnter
F1,F1
F2,F2
F3,F3
F4,F4
F5,F5
F6,F6
F7,F7
F8,F8
F9,F9
F10,F10
F11,F11
F12,F12
F13,F13
F14,F14
F15,F15
F16,F16
F17,F17
F18,F18
F19,F19
F20,F20
F21,F21
F22,F22
F23,F23
F24,F24
LWin,LWin
RWin,RWin
Control,Control
Ctrl,Control
Alt,Alt
Shift,Shift
LControl,LControl
LCtrl,LControl
RControl,RControl
RCtrl,RControl
LShift,LShift
RShift,RShift
LAlt,LAlt
RAlt,RAlt
Browser_Back,Browser_Back
Browser_Forward,Browser_Forward
Browser_Refresh,Browser_Refresh
Browser_Stop,Browser_Stop
Browser_Search,Browser_Search
Browser_Favorites,Browser_Favorites
Browser_Home,Browser_Home
Volume_Mute,Volume_Mute
Volume_Down,Volume_Down
Volume_Up,Volume_Up
Media_Next,Media_Next
Media_Prev,Media_Prev
Media_Stop,Media_Stop
Media_Play_Pause,Media_Play_Pause
Launch_Mail,Launch_Mail
Launch_Media,Launch_Media
Launch_App1,Launch_App1
Launch_App2,Launch_App2
AppsKey,AppsKey
PrintScreen,PrintScreen
CtrlBreak,CtrlBreak
Pause,Pause
Help,Help
Sleep,Sleep
Joy1,Joy1
Joy2,Joy2
Joy3,Joy3
Joy4,Joy4
Joy5,Joy5
Joy6,Joy6
Joy7,Joy7
Joy8,Joy8
Joy9,Joy9
Joy10,Joy10
Joy11,Joy11
Joy12,Joy12
Joy13,Joy13
Joy14,Joy14
Joy15,Joy15
Joy16,Joy16
Joy17,Joy17
Joy18,Joy18
Joy19,Joy19
Joy20,Joy20
Joy21,Joy21
Joy22,Joy22
Joy23,Joy23
Joy24,Joy24
Joy25,Joy25
Joy26,Joy26
Joy27,Joy27
Joy28,Joy28
Joy29,Joy29
Joy30,Joy30
Joy31,Joy31
Joy32,Joy32
)"
    fn:=(VerCompare(A_AhkVersion,"2.0-")>=0 ?"Map" :"Object"), map_keylist:=%fn%()
    VerCompare(A_AhkVersion,"2.0-") ?map_keylist.CaseSense:=vcasesense :""
    For i,v in StrSplit(str_keylist,"`n")
        vsplit:=StrSplit(v,","), map_keylist[vsplit[1]]:=vsplit[2]
    return map_keylist
}
